agent_name: swapping_agent
author: isotrop
version: 0.1.0
license: Apache-2.0
description: A data fetching agent for swapping.
aea_version: '>=1.19.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeie4eixvrdpc5ifoovj24a6res6g2e22dl6di6gzib7d3fczshzyti
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/http_server:0.22.0:bafybeihpgu56ovmq4npazdbh6y6ru5i7zuv6wvdglpxavsckyih56smu7m
- valory/ipfs:0.1.0:bafybeiefkqvh5ylbk77xylcmshyuafmiecopt4gvardnubq52psvogis6a
- valory/ledger:0.19.0:bafybeihynkdraqthjtv74qk3nc5r2xubniqx2hhzpxn7bd4qmlf7q4wruq
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts: []
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- valory/abstract_abci:0.1.0:bafybeihu2bcgjk2tqjiq2zhk3uogtfszqn4osvdt7ho3fubdpdj4jgdfjm
- valory/abstract_round_abci:0.1.0:bafybeibovsktd3uxur45nrcomq5shcn46cgxd5idmhxbmjhg32c5abyqim
- isotrop/swapping_abci:0.1.0:bafybeibk4x5jjj63wddskf7z62xaxrbdoop4mynmqlbnyvgccbfqhcsvki
- isotrop/swapping_chained_abci:0.1.0:bafybeih4q7b6gl6m66dx4g6rgupjndvida2h6xh6y6p7fby5pqkxnhwapu
- valory/registration_abci:0.1.0:bafybeicnth5q4httefsusywx3zrrq4al47owvge72dqf2fziruicq6hqta
- valory/reset_pause_abci:0.1.0:bafybeievjciqdvxhqxfjd4whqs27h6qbxqzrae7wwj7fpvxlvmtw3x35im
- valory/termination_abci:0.1.0:bafybeid54buqxipiuduw7b6nnliiwsxajnltseuroad53wukfonpxca2om
- valory/transaction_settlement_abci:0.1.0:bafybeihq2yenstblmaadzcjousowj5kfn5l7ns5pxweq2gcrsczfyq5wzm
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.55.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: isotrop/swapping_chained_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
    gnosis:
      address: ${str:https://rpc.chiadochain.net}
      chain_id: ${int:1337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: isotrop/swapping_chained_abci:0.1.0
---
public_id: isotrop/swapping_chained_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/logs}
  params:
    args:
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0x0000000000000000000000000000000000000000}
      termination_sleep: ${int:900}
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:10}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:10}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: swapping
      service_registry_address: ${str:null}
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      use_termination: ${bool:false}
      tx_timeout: 10.0
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      multisend_batch_size: ${int:50}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      uni_router_address: ${str:0x1C232F01118CB8B424793ae03F870aa7D0ac7f77}
      target_tokens: ${str:wxdai:0xe91d153e0b41518a2ce8dd3d7944fa863463a97d,weth:0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1,usdc:0xddafbb505ad214d7b80b1f830fccc89b60fb7a83,link:0xe2e73a1c69ecf83f464efce6a5be353a37ca09b2,uni:0x4537e328bf7e4efa29d05caea260d7fe26af9d74,crv:0x712b3d230F3C1c19db860d80619288b1F0BDd0Bd,wbtc:0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252,grt:0xFAdc59D012Ba3c110B08A15B7755A5cb7Cbe77D7}
      token_address: ${str:0xcE11e14225575945b8E6Dc0D4F2dD4C570f79d9f}
      default_chain_id: ${str:gnosis}
      termination_from_block: ${int:34088325}
      default_xdai_val: ${int:800}
      rebalancing:
        chain: gnosis
        token_base_address: '0xe91d153e0b41518a2ce8dd3d7944fa863463a97d'
        token_base_ticker: WXDAI
        token_a_address: '0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1'
        token_a_ticker: WETH
        token_b_address: '0xddafbb505ad214d7b80b1f830fccc89b60fb7a83'
        token_b_ticker: USDC
        token_c_address: '0xe2e73a1c69ecf83f464efce6a5be353a37ca09b2'
        token_c_ticker: LINK
        token_d_address: '0x4537e328bf7e4efa29d05caea260d7fe26af9d74'
        token_d_ticker: UNI
        token_e_address: '0x712b3d230F3C1c19db860d80619288b1F0BDd0Bd'
        token_e_ticker: CRV
        token_f_address: '0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252'
        token_f_ticker: WBTC
        token_g_address: '0xFAdc59D012Ba3c110B08A15B7755A5cb7Cbe77D7'
        token_g_ticker: GRT
        lp_token_address: '0x7bea4af5d425f2d4485bdad1859c88617df31a67'
        default_minter: '0x0000000000000000000000000000000000000000'
        ab_pool_address: '0x86A6C37D3E868580a65C723AAd7E0a945E170416'
        max_allowance: 1.0e+18
        default_max_allowance: 2000000000000000000
        deadline: 300
        sleep_seconds: 1
